#!/bin/bash
AF_CFG="/sobaka/cfg/af.cfg"

#Sample af.cfg:
sample_cfg='
{
  "af_enabled": 1,
  "af_tt": 62,
  "af_hyst": 1,
  "af_fanmin": 40,
  "af_fanmax": 100,
  "af_shift": 5,
  "af_delay": 12
}'

#colors section (somebody can use it without SobakaOS)
RED="\e[31m"
WHITE="\e[0m"
GREEN="\e[32m"
BROWN="\e[33m"
BLUE="\e[34m"
PURPLE="\e[35m"
CYAN="\e[36m"
LINE="echo -e $BROWN================================================================$WHITE"
up="↗"
down="↘"
#colors section end

function dependency_check () {
	dependency_version=`dpkg -s $1 2>&1 | grep '^Version: ' | sed 's/Version: //'`
	if [[ -z "$dependency_version" ]]; then
		echo -e ">$1 is not installed, installing"
		apt-get update
		apt-get install --reinstall -y $1
	fi
}

dependency_check screen
dependency_check jq

function screen_kill () {
	local MINER_PID=$(screen -ls | grep "$1" | sed 's/\s\([0-9]*\)..*/\1/')
	[[ ! -z $MINER_PID ]]&& kill $MINER_PID
}

function displaytime () {
  local T=$1
  local D=$((T/60/60/24))
  local H=$((T/60/60%24))
  local M=$((T/60%60))
  local S=$((T%60))
  [[ $D > 0 ]] && printf '%d days ' $D
  [[ $H > 0 ]] && printf '%d hours ' $H
  [[ $M > 0 ]] && printf '%d min ' $M
  printf '%d sec\n' $S
}

function set_fan_amd () {
	local fan=$1
	local fan_addr=$2
	echo 1 > $fan_addr/pwm1_enable
	let local fan_adapted=$fan*255/100+2 #fan power is beetween 0 and 255
	[[ $fan_adapted -gt 255 ]] && fan_adapted=255
	echo $fan_adapted > $fan_addr/pwm1
}

function prepare_nvidia_args () {
	local fan=$1
	local i=$2
	nv_args+=" -a [gpu:$i]/GPUFanControlState=1"
	nv_args+=" -a [fan:$i]/GPUTargetFanSpeed=$fan"
	echo "$nv_args"
}

function autofan () {
	local nv_args=""
	local time=`date +%s`
	local secs=`echo "$time - $start_time" | bc -l`
	local hr_time=`displaytime $secs`
	local nvidia_smi=`nvidia-smi --query-gpu=index,gpu_bus_id,temperature.gpu,fan.speed --format=csv,noheader`
	echo -e "${GREEN}Target temp ${CYAN}$target_temp${GREEN}$C, hyst ${CYAN}$hyst${GREEN}, fan min/max ${BLUE}$fan_min${GREEN}/${RED}$fan_max${GREEN}, shift ${CYAN}$fan_shift${GREEN}, delay ${CYAN}$delay${WHITE}"
	
	echo -e `date -R`" (working "$hr_time")\n"
	for (( i=0; i < ${#core_addr[@]}; i++ )); do
		if [ $(cat ${core_addr[$i]}/uevent | grep "DRIVER" | \
			sed -e 's/DRIVER\=\([a-z]*\)/\1/') == amdgpu ]; then
	
			local fan_addr[$i]=$(ls -d ${core_addr[$i]}/hwmon/hwmon[0-9]*)
			local gpu_fan[$i]=$(($(cat "${fan_addr[$i]}/pwm1") * 100 / 255))
			local gpu_temp_raw[$i]=`cat "${fan_addr[$i]}/temp1_input"` #temp1_input - current temp 
			local gpu_temp[$i]=$(echo "scale=0; ${gpu_temp_raw[$i]}/1000" | bc -l) #temp format is something like 65000
			local gpu_brand[$i]="AMD"
		elif [ $(cat ${core_addr[$i]}/uevent | grep "DRIVER" | \
			sed 's/DRIVER\=\([a-z]*\)/\1/') == nvidia ]; then #GPU is NVIDIA
	
			local nvidiainfo=`echo "$nvidia_smi" | grep -i ${gpu_busid_sys[$i]}":00.0"`
			local gpu_index[$i]=`awk -F ', ' '{print $1}' <<< $nvidiainfo`
			local gpu_temp[$i]=`awk -F ', ' '{print $3}' <<< $nvidiainfo`
			local gpu_fan[$i]=$(echo `awk -F ', ' '{print $4}' <<< $nvidiainfo` | sed 's/ %//')
			local gpu_brand[$i]="NVIDIA"
		fi
		[[ -z ${gpu_brand[$i]} ]] && continue
		
		if (( ${gpu_temp[$i]} - $hyst > $target_temp )); then #high temp
			local temp_color=$RED
			if [[ ${gpu_fan[$i]} -gt $fan_max ]]; then
				local new_fan[i]=$fan_max
				local fan_color=$RED
				local message="${CYAN}$down ${new_fan[$i]}${WHITE}"
			elif [[ ${gpu_fan[$i]} -lt $fan_max ]]; then
				local new_fan[i]=$((${gpu_fan[$i]} + $fan_shift))
				[[ ${new_fan[$i]} -gt $fan_max ]] && new_fan[$i]=$fan_max
				local message="${CYAN}$up ${new_fan[$i]}${WHITE}"
			else
				local fan_color=$RED
				local message="${RED}Max %${WHITE}"
			fi
		elif (( ${gpu_temp[$i]} + $hyst < $target_temp )); then #low temp
			local temp_color=$BLUE
			if [[ ${gpu_fan[$i]} -lt $fan_min ]];then
				local new_fan[i]=$fan_min
				local fan_color=$BLUE
				local message="${CYAN}$up ${new_fan[$i]}${WHITE}"
			elif [[ ${gpu_fan[$i]} -gt $fan_min ]];then
				local new_fan[i]=$((${gpu_fan[$i]} - $fan_shift))
				[[ ${new_fan[$i]} -lt $fan_min ]] && new_fan[$i]=$fan_min
				local message="${CYAN}$down ${new_fan[$i]}${WHITE}"
			else
				local fan_color=$BLUE
				local message="${BLUE}Min %${WHITE}" 
			fi
		fi
		[[ -z $temp_color ]] && temp_color=$WHITE
		[[ -z $fan_color ]] && fan_color="$WHITE"
		
		string="${CYAN}$i${WHITE} ${gpu_busid_sys[$i]}:00.0 ${gpu_brand[$i]}\t"
		string+="Temp: ${temp_color}${gpu_temp[$i]}${WHITE}°C\t"
		
		#fucking bug because white is shorter than red
		[[ "$temp_color" != "$WHITE" ]] && string+=" " 
		string+="Fan: ${fan_color}${gpu_fan[$i]}${WHITE} "
		if [[ ${gpu_fan[$i]} -ge 10 &&  ${gpu_fan[$i]} -lt 100 ]]; then
			string+=" "
		elif [[ ${gpu_fan[$i]} -lt 10 ]]; then
			string+="  "
		fi
		string+="$message"
		#echo $string
		echo -e "$string"
		
		#Set fan if something changed
		if [[ ! -z ${new_fan[$i]} ]]; then
			if [[ ${gpu_brand[$i]} == "AMD" ]]; then
				set_fan_amd ${new_fan[i]} ${fan_addr[$i]}
			elif [[ ${gpu_brand[$i]} == "NVIDIA" ]]; then
				#local result=`set_fan_nvidia ${new_fan[i]} ${gpu_index[$i]}`
				nv_args=`prepare_nvidia_args ${new_fan[i]} ${gpu_index[$i]}`
			fi
		fi
		#echo -e " $result"
		
		unset temp_color fan_color message result new_fan
	done
	[[ ! -z $nv_args ]] && nvidia-settings$nv_args >/dev/null 2>&1
	$LINE
}

function start () {
	start_time=`date +%s`
	
	if [[ -f $AF_CFG ]]; then
		cfg=`cat $AF_CFG`
	else
		echo -e "${RED}You don\`t have config file $AF_CFG, using standart config${WHITE}"
		cfg=$sample_cfg
	fi
	
	enabled=`echo $cfg | jq '.af_enabled'`
	[[ $enabled -ne 1 ]] && echo -e "${RED}Autofan is not enabled, exit${WHITE}" && exit 1
	target_temp=`echo $cfg | jq '.af_tt'`
	hyst=`echo $cfg | jq '.af_hyst'`
	fan_shift=`echo $cfg | jq '.af_shift'`
	fan_max=`echo $cfg | jq '.af_fanmax'`
	fan_min=`echo $cfg | jq '.af_fanmin'`
	delay=`echo $cfg | jq '.af_delay'`
	
	echo -e "${GREEN}Thank you for using ${CYAN}SobakaOS${GREEN} autofan v 0.2"
	$LINE
	
	export DISPLAY=:0

	core_addr_raw=(`ls -d /sys/class/drm/card[0-9]*/device | egrep 'card[0-9]{1,2}/'`)
	
	for (( i=0; i < ${#core_addr_raw[@]}; i++ )); do
		gpu_busid_raw[$i]=$(cat ${core_addr_raw[$i]}/uevent | grep "PCI_SLOT_NAME" | sed 's/.*0000:\([0-9abcdefABCDEF]*\):.*/\1/')
	done
			
	IFS=$'\n' gpu_busid_sys=($(sort <<<"${gpu_busid_raw[*]}"))
	unset IFS
	for (( i=0; i < ${#gpu_busid_raw[@]}; i++ )) do
		for (( y=0; y < ${#gpu_busid_raw[@]}; y++ )) do
			[[ ${gpu_busid_sys[$i]} == ${gpu_busid_raw[$y]} ]] && core_addr[$i]=${core_addr_raw[$y]} && break
		done
	done
	
	while true; do
		autofan
		sleep $delay
	done
}

case $1 in
	show|"")
		screen -d af
		screen -r af
	;;
	stop)
		screen_kill af
		echo "$(date --rfc-3339=seconds) Autofan stopped"
	;;
	start_cli)
		start
	;;
	start|restart)
		screen_kill af
		screen -dmS af bash -c "$0 start_cli"
		echo "$(date --rfc-3339=seconds) Autofan (re)started"
	;;
	*)
		bname=`basename $0`
		echo -e "Usage: ${CYAN}$bname show|start|stop|restart|start_cli${WHITE}"
	;;
esac